# === JDBC / Agroal ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER}
quarkus.datasource.password=${POSTGRESQL_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/ordersdb
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.min-size=2

# Canal de saida (Producer -> Kafka). O broker fica interno no cluster pelo
# Service bootstrap criado pelo AMQ Streams.
kafka.bootstrap.servers=orders-kafka-kafka-bootstrap:9092
mp.messaging.outgoing.orders-out.connector=smallrye-kafka
mp.messaging.outgoing.orders-out.topic=orders
mp.messaging.outgoing.orders-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# === OpenShift deploy ===
quarkus.openshift.deploy=false
quarkus.openshift.route.expose=false
quarkus.openshift.env.secrets=postgres-secret
